- PostgreSQL, Postgres
- MongoDB
- DynamoDB
- Cassandra
- Microsoft SQL Server
- MySQL
- Amazon DynamoDB
- Apache Solr
- IBM Db2 warehouse
- neo4j
- Oracle PL/SQL
- Google BigQuery
- Snowflake
- Apache Hive
- Microsoft SQL Server
- Oracle Exadata
- IBM Db2 Warehouse
- SAP HANA
- Teradata
- Informatica PowerCenter
- Data Bricks, Databricks
- Presto
- Amazon Redshift
